In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import RobustScaler

In [3]:
df = pd.read_csv("creditcard.csv")

In [5]:
df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

RobustScaler - Normalization

In [6]:
robus = RobustScaler()
df['scaled_amount'] = robus.fit_transform(df['Amount'].values.reshape(-1,1))
df['scaled_time'] = robus.fit_transform(df['Time'].values.reshape(-1,1))

df.drop(['Amount','Time'],axis=1,inplace=True)

s_amnt = df['scaled_amount']
s_time = df['scaled_time']

df.drop(['scaled_amount','scaled_time'],axis=1,inplace=True)
df.insert(0,'scaled_amount',s_amnt)
df.insert(1,'scaled_time',s_time)

print(df.head())

   scaled_amount  scaled_time        V1        V2        V3        V4  \
0       1.783274    -0.994983 -1.359807 -0.072781  2.536347  1.378155
1      -0.269825    -0.994983  1.191857  0.266151  0.166480  0.448154
2       4.983721    -0.994972 -1.358354 -1.340163  1.773209  0.379780
3       1.418291    -0.994972 -0.966272 -0.185226  1.792993 -0.863291
4       0.670579    -0.994960 -1.158233  0.877737  1.548718  0.403034

         V5        V6        V7        V8  ...       V20       V21       V22  \
0 -0.338321  0.462388  0.239599  0.098698  ...  0.251412 -0.018307  0.277838
1  0.060018 -0.082361 -0.078803  0.085102  ... -0.069083 -0.225775 -0.638672
2 -0.503198  1.800499  0.791461  0.247676  ...  0.524980  0.247998  0.771679
3 -0.010309  1.247203  0.237609  0.377436  ... -0.208038 -0.108300  0.005274
4 -0.407193  0.095921  0.592941 -0.270533  ...  0.408542 -0.009431  0.798278

        V23       V24       V25       V26       V27       V28  Class
0 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053      0
1  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724      0
2  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752      0
3 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458      0
4 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153      0

[5 rows x 31 columns]

In [7]:
df

,scaled_amount,scaled_time,V1,V2,V3,V4,V5,V6,V7,V8,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Class
0,1.783274,-0.994983,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,...,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,0
1,-0.269825,-0.994983,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,...,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,0
2,4.983721,-0.994972,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,...,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,0
3,1.418291,-0.994972,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,...,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,0
4,0.670579,-0.994960,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,...,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,-0.296653,1.034951,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,...,1.475829,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0
284803,0.038986,1.034963,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,...,0.059616,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,0
284804,0.641096,1.034975,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,...,0.001396,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,0
284805,-0.167680,1.034975,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,...,0.127434,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,0
284806,2.724796,1.035022,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,...,0.382948,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,0

In [8]:
from sklearn.model_selection import train_test_split

X=df.drop(['Class'],axis=1)
y=df['Class']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [9]:
print(y_test.sum())

98

XGBOOST

In [26]:
# Install optuna if not already installed
%pip install optuna --quiet

import optuna
import xgboost as xgb
from sklearn.metrics import average_precision_score

def objective(trial):
    # 1. Define the search space (Hyperparameters)
    param = {
        'verbosity': 0,
        'objective': 'binary:logistic',
        'eval_metric': 'aucpr',
        'n_estimators': trial.suggest_int('n_estimators', 100, 1000),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 1e-3, 0.3, log=True),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'scale_pos_weight': trial.suggest_float('scale_pos_weight', 1, 100), # Very useful for fraud/imbalance
    }

    # 2. Initialize and train the model
    model = xgb.XGBClassifier(**param)
    model.fit(X_train, y_train)

    # 3. Predict probabilities and calculate AUPRC
    preds = model.predict_proba(X_test)[:, 1]
    aucpr = average_precision_score(y_test, preds)

    return aucpr

# 4. Create a study and run optimization
study = optuna.create_study(direction='maximize') # We want to maximize AUCPR
study.optimize(objective, n_trials=20) # Try 20 different combinations

print(f"Best AUCPR: {study.best_value}")
print(f"Best params: {study.best_params}")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 7.8 MB/s eta 0:00:00

[I 2026-03-31 21:16:05,644] A new study created in memory with name: no-name-4151af50-0b74-448a-87c5-279b3bbc2bc7
[I 2026-03-31 21:16:27,066] Trial 0 finished with value: 0.8304825030655398 and parameters: {'n_estimators': 447, 'max_depth': 8, 'learning_rate': 0.002773113977242086, 'subsample': 0.8566289975675052, 'colsample_bytree': 0.6507723239083317, 'scale_pos_weight': 16.881525284072737}. Best is trial 0 with value: 0.8304825030655398.
[I 2026-03-31 21:16:52,702] Trial 1 finished with value: 0.8850401176020807 and parameters: {'n_estimators': 722, 'max_depth': 7, 'learning_rate': 0.18303260956522854, 'subsample': 0.9953228473889706, 'colsample_bytree': 0.7435397968139709, 'scale_pos_weight': 41.07115023588834}. Best is trial 1 with value: 0.8850401176020807.
[I 2026-03-31 21:17:18,427] Trial 2 finished with value: 0.7282006573158752 and parameters: {'n_estimators': 770, 'max_depth': 5, 'learning_rate': 0.0013004876486909745, 'subsample': 0.9713862561831297, 'colsample_bytree': 0.9880710764896132, 'scale_pos_weight': 26.148956534177323}. Best is trial 1 with value: 0.8850401176020807.
[I 2026-03-31 21:17:47,989] Trial 3 finished with value: 0.7939621946966753 and parameters: {'n_estimators': 738, 'max_depth': 7, 'learning_rate': 0.0012014973245611162, 'subsample': 0.7174186422479976, 'colsample_bytree': 0.5799058924657626, 'scale_pos_weight': 18.85496401059463}. Best is trial 1 with value: 0.8850401176020807.
[I 2026-03-31 21:17:58,096] Trial 4 finished with value: 0.8564524962747567 and parameters: {'n_estimators': 160, 'max_depth': 8, 'learning_rate': 0.01562098057796716, 'subsample': 0.610674266742015, 'colsample_bytree': 0.8351774549005141, 'scale_pos_weight': 24.45903544719281}. Best is trial 1 with value: 0.8850401176020807.
[I 2026-03-31 21:18:24,979] Trial 5 finished with value: 0.8642481388317165 and parameters: {'n_estimators': 472, 'max_depth': 9, 'learning_rate': 0.015771801257375154, 'subsample': 0.5893750269293538, 'colsample_bytree': 0.6758631212971247, 'scale_pos_weight': 89.39752783685651}. Best is trial 1 with value: 0.8850401176020807.
[I 2026-03-31 21:19:09,002] Trial 6 finished with value: 0.7870263413773927 and parameters: {'n_estimators': 841, 'max_depth': 9, 'learning_rate': 0.002726391224465473, 'subsample': 0.5246573914158481, 'colsample_bytree': 0.8801721285606982, 'scale_pos_weight': 77.5777125527715}. Best is trial 1 with value: 0.8850401176020807.
[I 2026-03-31 21:19:34,227] Trial 7 finished with value: 0.8273101070214188 and parameters: {'n_estimators': 798, 'max_depth': 4, 'learning_rate': 0.003686494184280797, 'subsample': 0.6220013137563022, 'colsample_bytree': 0.8940605454562811, 'scale_pos_weight': 16.176482839235433}. Best is trial 1 with value: 0.8850401176020807.
[I 2026-03-31 21:19:57,889] Trial 8 finished with value: 0.8756256680214274 and parameters: {'n_estimators': 595, 'max_depth': 4, 'learning_rate': 0.059555875771160824, 'subsample': 0.6837837503299542, 'colsample_bytree': 0.8518449897365654, 'scale_pos_weight': 15.221729004492477}. Best is trial 1 with value: 0.8850401176020807.
[I 2026-03-31 21:20:08,973] Trial 9 finished with value: 0.7230848734307334 and parameters: {'n_estimators': 269, 'max_depth': 6, 'learning_rate': 0.0010488026874970512, 'subsample': 0.5319023538901603, 'colsample_bytree': 0.7607959382108527, 'scale_pos_weight': 60.255638845444814}. Best is trial 1 with value: 0.8850401176020807.
[I 2026-03-31 21:20:37,664] Trial 10 finished with value: 0.8821471603114424 and parameters: {'n_estimators': 943, 'max_depth': 10, 'learning_rate': 0.2861821701648325, 'subsample': 0.9969923271551662, 'colsample_bytree': 0.5291208184502441, 'scale_pos_weight': 45.85509079918622}. Best is trial 1 with value: 0.8850401176020807.
[I 2026-03-31 21:21:07,278] Trial 11 finished with value: 0.8809224762218645 and parameters: {'n_estimators': 999, 'max_depth': 10, 'learning_rate': 0.2826528613425457, 'subsample': 0.9994518373019623, 'colsample_bytree': 0.5035469441868115, 'scale_pos_weight': 45.424405311511016}. Best is trial 1 with value: 0.8850401176020807.
[I 2026-03-31 21:21:37,353] Trial 12 finished with value: 0.8770393316706977 and parameters: {'n_estimators': 985, 'max_depth': 10, 'learning_rate': 0.23856754993415602, 'subsample': 0.883069353212887, 'colsample_bytree': 0.5007338875095202, 'scale_pos_weight': 43.86154160823426}. Best is trial 1 with value: 0.8850401176020807.
[I 2026-03-31 21:22:03,568] Trial 13 finished with value: 0.8874261046490974 and parameters: {'n_estimators': 624, 'max_depth': 6, 'learning_rate': 0.09158394122314287, 'subsample': 0.8916207851064806, 'colsample_bytree': 0.72760681006436, 'scale_pos_weight': 61.32861467851913}. Best is trial 13 with value: 0.8874261046490974.
[I 2026-03-31 21:22:31,060] Trial 14 finished with value: 0.885135797941737 and parameters: {'n_estimators': 621, 'max_depth': 6, 'learning_rate': 0.08257325520088747, 'subsample': 0.8469073040990899, 'colsample_bytree': 0.7295478446853453, 'scale_pos_weight': 66.67721469886172}. Best is trial 13 with value: 0.8874261046490974.
[I 2026-03-31 21:22:57,992] Trial 15 finished with value: 0.8822626762509056 and parameters: {'n_estimators': 603, 'max_depth': 6, 'learning_rate': 0.056669049255051805, 'subsample': 0.8155501272323213, 'colsample_bytree': 0.748453161470329, 'scale_pos_weight': 66.47517604571424}. Best is trial 13 with value: 0.8874261046490974.
[I 2026-03-31 21:23:09,755] Trial 16 finished with value: 0.8475391750015272 and parameters: {'n_estimators': 371, 'max_depth': 3, 'learning_rate': 0.07720666942663162, 'subsample': 0.7881057571168761, 'colsample_bytree': 0.6720764596546013, 'scale_pos_weight': 97.41877333842109}. Best is trial 13 with value: 0.8874261046490974.
[I 2026-03-31 21:23:35,897] Trial 17 finished with value: 0.883020965788041 and parameters: {'n_estimators': 659, 'max_depth': 5, 'learning_rate': 0.03161742766368251, 'subsample': 0.9087852868177635, 'colsample_bytree': 0.6085706816856606, 'scale_pos_weight': 74.18035905655728}. Best is trial 13 with value: 0.8874261046490974.
[I 2026-03-31 21:23:56,513] Trial 18 finished with value: 0.8775247429949533 and parameters: {'n_estimators': 507, 'max_depth': 5, 'learning_rate': 0.10915334115903444, 'subsample': 0.9133448143401903, 'colsample_bytree': 0.7956228318798378, 'scale_pos_weight': 1.1127091197344967}. Best is trial 13 with value: 0.8874261046490974.
[I 2026-03-31 21:24:12,609] Trial 19 finished with value: 0.8762237449822211 and parameters: {'n_estimators': 350, 'max_depth': 6, 'learning_rate': 0.0269969822983104, 'subsample': 0.7690403447955277, 'colsample_bytree': 0.7128326080759578, 'scale_pos_weight': 56.96263817686291}. Best is trial 13 with value: 0.8874261046490974.

Best AUCPR: 0.8874261046490974
Best params: {'n_estimators': 624, 'max_depth': 6, 'learning_rate': 0.09158394122314287, 'subsample': 0.8916207851064806, 'colsample_bytree': 0.72760681006436, 'scale_pos_weight': 61.32861467851913}

In [27]:
from sklearn.metrics import average_precision_score, accuracy_score
best_params = study.best_params
final_model = xgb.XGBClassifier(**best_params)
final_model.fit(X_train,y_train)
y_pred = final_model.predict(X_test)
y_pred_probab = final_model.predict_proba(X_test)[:,1]
aucpr_score = average_precision_score(y_test, y_pred_probab)

print(f"AUCPR Score: {aucpr_score:.4f}")
print(f"Accuracy: {accuracy_score(y_test, y_pred) * 100:.2f}%")

AUCPR Score: 0.8874
Accuracy: 99.96%

Confusion matrix and accuracy score

In [28]:
con_matrix = confusion_matrix(y_test, y_pred)
print(con_matrix)

[[56857     7]
 [   16    82]]

Random Forest

In [29]:
from sklearn.ensemble import RandomForestClassifier

In [30]:
from sklearn.ensemble import RandomForestClassifier

def objective_rf(trial):
    param = {
        'n_estimators': trial.suggest_int('n_estimators', 50, 500),
        'max_depth': trial.suggest_int('max_depth', 5, 30),
        'min_samples_split': trial.suggest_int('min_samples_split', 2, 10),
        'criterion': trial.suggest_categorical('criterion', ['gini', 'entropy']),
        'class_weight': 'balanced', # Important for imbalanced fraud data
        'n_jobs': -1 # Uses all CPU cores to speed up training
    }

    model = RandomForestClassifier(**param)
    model.fit(X_train, y_train)

    preds = model.predict_proba(X_test)[:, 1]
    return average_precision_score(y_test, preds)

study_rf = optuna.create_study(direction='maximize')
study_rf.optimize(objective_rf, n_trials=15)

[I 2026-03-31 21:43:57,311] A new study created in memory with name: no-name-28b2cf41-a1da-4a7d-aeb5-0d75cd451833
[I 2026-03-31 21:55:03,354] Trial 0 finished with value: 0.8740412991633363 and parameters: {'n_estimators': 457, 'max_depth': 18, 'min_samples_split': 8, 'criterion': 'entropy'}. Best is trial 0 with value: 0.8740412991633363.
[I 2026-03-31 22:02:09,405] Trial 1 finished with value: 0.8717538988946403 and parameters: {'n_estimators': 290, 'max_depth': 13, 'min_samples_split': 9, 'criterion': 'entropy'}. Best is trial 0 with value: 0.8740412991633363.
[I 2026-03-31 22:05:51,902] Trial 2 finished with value: 0.8701869034616108 and parameters: {'n_estimators': 150, 'max_depth': 25, 'min_samples_split': 8, 'criterion': 'entropy'}. Best is trial 0 with value: 0.8740412991633363.
[I 2026-03-31 22:15:27,343] Trial 3 finished with value: 0.849139768563631 and parameters: {'n_estimators': 378, 'max_depth': 17, 'min_samples_split': 10, 'criterion': 'gini'}. Best is trial 0 with value: 0.8740412991633363.
[I 2026-03-31 22:23:46,450] Trial 4 finished with value: 0.8526091351926202 and parameters: {'n_estimators': 332, 'max_depth': 29, 'min_samples_split': 9, 'criterion': 'gini'}. Best is trial 0 with value: 0.8740412991633363.
[I 2026-03-31 22:31:36,145] Trial 5 finished with value: 0.871178228083498 and parameters: {'n_estimators': 322, 'max_depth': 19, 'min_samples_split': 9, 'criterion': 'entropy'}. Best is trial 0 with value: 0.8740412991633363.
[I 2026-03-31 22:39:04,366] Trial 6 finished with value: 0.8290940864269972 and parameters: {'n_estimators': 305, 'max_depth': 11, 'min_samples_split': 8, 'criterion': 'gini'}. Best is trial 0 with value: 0.8740412991633363.
[I 2026-03-31 22:47:37,871] Trial 7 finished with value: 0.7993399990572455 and parameters: {'n_estimators': 377, 'max_depth': 9, 'min_samples_split': 2, 'criterion': 'gini'}. Best is trial 0 with value: 0.8740412991633363.
[I 2026-03-31 22:57:43,944] Trial 8 finished with value: 0.837964862563523 and parameters: {'n_estimators': 478, 'max_depth': 7, 'min_samples_split': 8, 'criterion': 'entropy'}. Best is trial 0 with value: 0.8740412991633363.
[I 2026-03-31 23:04:57,331] Trial 9 finished with value: 0.8745358377299328 and parameters: {'n_estimators': 301, 'max_depth': 26, 'min_samples_split': 6, 'criterion': 'entropy'}. Best is trial 9 with value: 0.8745358377299328.
[I 2026-03-31 23:09:12,878] Trial 10 finished with value: 0.8677963972137952 and parameters: {'n_estimators': 176, 'max_depth': 24, 'min_samples_split': 5, 'criterion': 'entropy'}. Best is trial 9 with value: 0.8745358377299328.
[I 2026-03-31 23:20:33,515] Trial 11 finished with value: 0.8733607551011536 and parameters: {'n_estimators': 467, 'max_depth': 20, 'min_samples_split': 5, 'criterion': 'entropy'}. Best is trial 9 with value: 0.8745358377299328.
[I 2026-03-31 23:25:45,096] Trial 12 finished with value: 0.8734875734744026 and parameters: {'n_estimators': 213, 'max_depth': 28, 'min_samples_split': 6, 'criterion': 'entropy'}. Best is trial 9 with value: 0.8745358377299328.
[I 2026-03-31 23:36:16,518] Trial 13 finished with value: 0.8729591180552311 and parameters: {'n_estimators': 427, 'max_depth': 16, 'min_samples_split': 3, 'criterion': 'entropy'}. Best is trial 9 with value: 0.8745358377299328.
[I 2026-03-31 23:38:40,960] Trial 14 finished with value: 0.8730922358835673 and parameters: {'n_estimators': 99, 'max_depth': 25, 'min_samples_split': 6, 'criterion': 'entropy'}. Best is trial 9 with value: 0.8745358377299328.

In [36]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import average_precision_score, accuracy_score

# 1. Trial 9 parameters (The Winners)
best_rf_params = {
    'n_estimators': 99,
    'max_depth': 25,
    'min_samples_split': 6,
    'criterion': 'entropy',
    'class_weight': 'balanced',
    'n_jobs': -1
}

# 2. Re-initialize and fit (Should take 2-3 mins max)
final_model_rf = RandomForestClassifier(**best_rf_params)
final_model_rf.fit(X_train, y_train)

# 3. Final Predictions & Evaluation
y_pred_rf = final_model_rf.predict(X_test)
y_prob_rf = final_model_rf.predict_proba(X_test)[:, 1]

final_aucpr_rf = average_precision_score(y_test, y_prob_rf)
final_acc_rf = accuracy_score(y_test, y_pred_rf)

print(f"--- Final Random Forest Results (Trial 9) ---")
print(f"AUCPR Score: {final_aucpr_rf:.4f}")
print(f"Accuracy: {final_acc_rf * 100:.2f}%")

--- Final Random Forest Results (Trial 9) ---
AUCPR Score: 0.8744
Accuracy: 99.96%

Confusion Matrix

In [39]:
con_mat = confusion_matrix(y_test, y_pred_rf)
print(con_mat)

[[56861     3]
 [   22    76]]

Decision Trees

In [18]:
from sklearn.tree import DecisionTreeClassifier

In [40]:
from sklearn.tree import DecisionTreeClassifier

def objective_dt(trial):
    # 1. Define Search Space
    param = {
        'max_depth': trial.suggest_int('max_depth', 3, 30),
        'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 50),
        'criterion': trial.suggest_categorical('criterion', ['gini', 'entropy']),
        'class_weight': 'balanced' # Essential for imbalanced data
    }

    # 2. Train Model
    model = DecisionTreeClassifier(**param)
    model.fit(X_train, y_train)

    # 3. Evaluate using AUCPR
    preds = model.predict_proba(X_test)[:, 1]
    return average_precision_score(y_test, preds)

# 4. Run Optimization
study_dt = optuna.create_study(direction='maximize')
study_dt.optimize(objective_dt, n_trials=20)

print(f"Best DT AUCPR: {study_dt.best_value:.4f}")

[I 2026-04-01 00:24:41,650] A new study created in memory with name: no-name-d4c9ac6e-53a3-486b-9f73-527181067dc9
[I 2026-04-01 00:24:58,746] Trial 0 finished with value: 0.7257927195081163 and parameters: {'max_depth': 30, 'min_samples_leaf': 11, 'criterion': 'gini'}. Best is trial 0 with value: 0.7257927195081163.
[I 2026-04-01 00:25:13,417] Trial 1 finished with value: 0.8041975871933059 and parameters: {'max_depth': 21, 'min_samples_leaf': 30, 'criterion': 'entropy'}. Best is trial 1 with value: 0.8041975871933059.
[I 2026-04-01 00:25:28,589] Trial 2 finished with value: 0.7641596846695946 and parameters: {'max_depth': 26, 'min_samples_leaf': 13, 'criterion': 'entropy'}. Best is trial 1 with value: 0.8041975871933059.
[I 2026-04-01 00:25:45,549] Trial 3 finished with value: 0.6971541057913313 and parameters: {'max_depth': 19, 'min_samples_leaf': 6, 'criterion': 'gini'}. Best is trial 1 with value: 0.8041975871933059.
[I 2026-04-01 00:26:00,107] Trial 4 finished with value: 0.6850570255504154 and parameters: {'max_depth': 19, 'min_samples_leaf': 5, 'criterion': 'entropy'}. Best is trial 1 with value: 0.8041975871933059.
[I 2026-04-01 00:26:14,707] Trial 5 finished with value: 0.6967096845955257 and parameters: {'max_depth': 24, 'min_samples_leaf': 8, 'criterion': 'entropy'}. Best is trial 1 with value: 0.8041975871933059.
[I 2026-04-01 00:26:32,472] Trial 6 finished with value: 0.7814077518872091 and parameters: {'max_depth': 25, 'min_samples_leaf': 47, 'criterion': 'gini'}. Best is trial 1 with value: 0.8041975871933059.
[I 2026-04-01 00:26:43,013] Trial 7 finished with value: 0.6512629025261394 and parameters: {'max_depth': 4, 'min_samples_leaf': 40, 'criterion': 'entropy'}. Best is trial 1 with value: 0.8041975871933059.
[I 2026-04-01 00:26:57,792] Trial 8 finished with value: 0.7921049234451513 and parameters: {'max_depth': 29, 'min_samples_leaf': 16, 'criterion': 'entropy'}. Best is trial 1 with value: 0.8041975871933059.
[I 2026-04-01 00:27:12,247] Trial 9 finished with value: 0.7995765374422775 and parameters: {'max_depth': 22, 'min_samples_leaf': 24, 'criterion': 'entropy'}. Best is trial 1 with value: 0.8041975871933059.
[I 2026-04-01 00:27:29,352] Trial 10 finished with value: 0.7441267904814186 and parameters: {'max_depth': 11, 'min_samples_leaf': 32, 'criterion': 'gini'}. Best is trial 1 with value: 0.8041975871933059.
[I 2026-04-01 00:27:43,714] Trial 11 finished with value: 0.7945747632190405 and parameters: {'max_depth': 14, 'min_samples_leaf': 25, 'criterion': 'entropy'}. Best is trial 1 with value: 0.8041975871933059.
[I 2026-04-01 00:27:58,665] Trial 12 finished with value: 0.8008571881262299 and parameters: {'max_depth': 21, 'min_samples_leaf': 23, 'criterion': 'entropy'}. Best is trial 1 with value: 0.8041975871933059.
[I 2026-04-01 00:28:13,033] Trial 13 finished with value: 0.8040153714498657 and parameters: {'max_depth': 14, 'min_samples_leaf': 33, 'criterion': 'entropy'}. Best is trial 1 with value: 0.8041975871933059.
[I 2026-04-01 00:28:27,387] Trial 14 finished with value: 0.7965072793491752 and parameters: {'max_depth': 10, 'min_samples_leaf': 34, 'criterion': 'entropy'}. Best is trial 1 with value: 0.8041975871933059.
[I 2026-04-01 00:28:42,056] Trial 15 finished with value: 0.8040153714498657 and parameters: {'max_depth': 14, 'min_samples_leaf': 32, 'criterion': 'entropy'}. Best is trial 1 with value: 0.8041975871933059.
[I 2026-04-01 00:28:56,163] Trial 16 finished with value: 0.7602298342248133 and parameters: {'max_depth': 6, 'min_samples_leaf': 41, 'criterion': 'entropy'}. Best is trial 1 with value: 0.8041975871933059.
[I 2026-04-01 00:29:10,442] Trial 17 finished with value: 0.7880414937169244 and parameters: {'max_depth': 16, 'min_samples_leaf': 19, 'criterion': 'entropy'}. Best is trial 1 with value: 0.8041975871933059.
[I 2026-04-01 00:29:28,353] Trial 18 finished with value: 0.7537104435469033 and parameters: {'max_depth': 10, 'min_samples_leaf': 36, 'criterion': 'gini'}. Best is trial 1 with value: 0.8041975871933059.
[I 2026-04-01 00:29:42,951] Trial 19 finished with value: 0.7686766988206357 and parameters: {'max_depth': 15, 'min_samples_leaf': 48, 'criterion': 'entropy'}. Best is trial 1 with value: 0.8041975871933059.

Best DT AUCPR: 0.8042

In [42]:
DescPred = study_dt.best_params
model_dt = DecisionTreeClassifier(**DescPred)
model_dt.fit(X_train,y_train)
model_predcit = model_dt.predict(X_test)
model_predict_probab = model_dt.predict_proba(X_test)[:,1]
model_predict_aucpr = average_precision_score(y_test, model_predict_probab)

print(f"AUCPR Score: {model_predict_aucpr:.4f}")
print(f"Accuracy: {accuracy_score(y_test, model_predcit) * 100:.2f}%")

AUCPR Score: 0.7993
Accuracy: 99.95%

confusion matrix

In [21]:
co_mat = confusion_matrix(y_test, DescPred)
print(co_mat)

[[56358   506]
 [   21    77]]